Dev
Alekseyt9/gameserver pull request #1
Opened 2024-06-17 09:37 UTC by Alekseyt9

Переделал ветки, чтобы в main было начальное состояние, а из dev пулреквест в main.

2024-06-17 15:00 UTC, gonozov0 requested changes
Отличная работа 👍
Хорошо структурировал и покрыл тестами
Оставил пару комментов

2024-06-17 15:00 UTC, gonozov0 commented on internal/services/processor_context.go
> +	sendMessages []model.SendMessage
Я правильно понимаю, что это история в рантайме будет изменяться из нескольких запросов?
Если да, то тебе нужно защитить изменения через RWMutex

2024-06-17 15:00 UTC, gonozov0 commented on internal/services/handlers/player_handler.go
> +	maxAge := 2147483647
почему такое магическое число?

2024-06-17 15:00 UTC, gonozov0 commented on internal/services/handlers/room_handler.go
> +	c.JSON(http.StatusOK, a)
Мне кажется правильнее будет проапгрейдить тут просто коннекшен до вебсокета и начать сразу его обработку, чем редиректить на другую ручку, тогда у тебя уйдет проблема с проверкой что такой playerID и roomID существует в /ws ручке

2024-06-17 15:00 UTC, gonozov0 commented on internal/services/matcher.go
> +	m.queue.lock.Lock()
ты тут обращаешься к приватному полю приватного поля, в моей картине мира этот код не должен скомпилироваться

2024-06-17 15:00 UTC, gonozov0 commented on internal/test/integration_test.go
> +			case 0:
А что это за стейты? введи enum для понимания и используй его тут

2024-06-19 13:51 UTC, Alekseyt9 commented
Дима, привет ! Спасибо за ревью, очень полезно! Поправил ошибки, написал ответы на комментарии.

2024-06-19 13:57 UTC, Alekseyt9 commented on internal/services/processor_context.go
> +	sendMessages []model.SendMessage
GameProcessorCtx меняется только из одного запроса для одной комнаты. Обработчик комнаты из канала (для этой конкретной комнаты) последовательно получает сообщения, создает GameProcessorCtx на один запрос и отправляет в обработчик игры. По крайней мере так планировалось, вроде так и работает. То есть разные комнаты обрабатываются параллельно, но для одной - все запросы выстраиваются в очередь через канал.

2024-06-19 13:59 UTC, Alekseyt9 commented on internal/services/handlers/player_handler.go
> +	maxAge := 2147483647
Тут просто беру максимальный int32 (максимальное число что позволяет api), написал немного по-другому, через константу

2024-06-19 14:04 UTC, Alekseyt9 commented on internal/services/handlers/room_handler.go
> +	c.JSON(http.StatusOK, a)
У меня не получилось проапгрейдить стандартное соединение (что-то жаловалось, что нужен спец заголовок). Но сделал иначе: вместо отдельного хендлера для вебсокета и для запроса - теперь только хендлер на коннект по вебсокету по url "/api/room/connect" и в нем все разруливается. А playerID и roomID помещается в хранилище сессии этого соединения (использую melody, обертку над gorilla). Тогда действительно не нужно снова поднимать комнату, а также проверять playerID. И хендлер только один.

2024-06-19 14:05 UTC, Alekseyt9 commented on internal/services/matcher.go
> +	m.queue.lock.Lock()
Поправил

2024-06-19 14:05 UTC, Alekseyt9 commented on internal/test/integration_test.go
> +			case 0:
Сделал енумы вместо чисел

2024-06-19 15:15 UTC, gonozov0 approved these changes
Отличная работа 💪
Все поправил, крутой прям проект получился 🔥

2024-06-19 21:04 UTC, merged